# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1fcb6c144c4e6cdf1d415f5e779edf92b4f77b23ea9dba9b01afe8e3ac12a8b6e2c459fe800d0592a0150108bac1c4c680eaebe215b89dd2c390eb926b2cc0dc

test:
  secret_key_base: ec9db65ab93062798bc5cbd7da343f8e06cea7a15a53c751eda4e5444952a97ef35f9299f36375986742a19cf6e51fc8412719929b893cb7ca2343a7c90421fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 29df0781f632129f9c3f4a2029f9a455a63c9616cc5c5fc66a4bc905656eeedde20572e71dba8b2bc4527d26a047a662c33f95ebf96f012cfe0eae65210be3cd
#<%= ENV["SECRET_KEY_BASE"] %>
